# Converted from XML console palette

[colors.primary]
background = "#000000"
foreground = "#c9c9c9"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.selection]
text = "#ffffff"
background = "#405f74"

[colors.normal]
black   = "#262626"
red     = "#405f74"
green   = "#8f9547"
yellow  = "#4e7d78"
blue    = "#802426"
magenta = "#714e76"
cyan    = "#d7a24d"
white   = "#c9c9c9"

[colors.bright]
black   = "#000000"
red     = "#8fb8dd"
green   = "#bac464"
yellow  = "#85cabf"
blue    = "#db6768"
magenta = "#cdaddd"
cyan    = "#eacc69"
white   = "#ffffff"

