set -g mouse on

set -g cursor-style bar
# set -g cursor-blink on

set -g default-terminal "tmux-256color"

bind r source-file ~/.tmux.conf \; display "Updated conf!"

# setw -g window-status-current-style 'bold'
set -g window-status-format "#I #W"

# Start windows & panes at 1st index
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

unbind C-b
set-option -g prefix C-z
bind-key C-z send-prefix

# VIM mode (WIP)
set-window-option -g mode-keys vi
bind v copy-mode

# v -> start selection
bind -T copy-mode-vi v send-keys -X begin-selection

# y -> copy without leaving copy mode
bind -T copy-mode-vi y send-keys -X copy-selection

# Style

# Rosé Pine 
set -g @rose_base      "#191724"
set -g @rose_surface   "#1f1d2e"
set -g @rose_overlay   "#26233a"
set -g @rose_muted     "#6e6a86"
set -g @rose_subtle    "#908caa"
set -g @rose_text      "#e0def4"
set -g @rose_love      "#eb6f92"
set -g @rose_gold      "#f6c177"
set -g @rose_rose      "#ebbcba"
set -g @rose_pine      "#31748f"
set -g @rose_foam      "#9ccfd8"
set -g @rose_iris      "#c4a7e7"
set -g @white_soft     "#fffaf3"

set -g status-position bottom
set -g status-justify left

set -g status-left-length 100
set -g status-right-length 100

set -gF status-style "fg=#{@rose_muted},bg=default"

set -g status-left "#[fg=#{@rose_love},bold] #S  "
# 「 #S 」

set -g status-right ' \
#[fg=#{@rose_iris}] \
#(branch=$(git -C "#{pane_current_path}" branch --show-current HEAD 2>/dev/null); \
[ -n "$branch" ] && echo " $branch ")'

set -g window-status-current-format "#[fg=#{@rose_foam}]#I:#W#[nounderscore]"
# set -g window-status-current-format "#[fg=#{@rose_foam}] ❯ #I:#W#[nounderscore]"

set -g message-style "fg=#{@rose_gold},bg=default"

set -g pane-active-border-style "fg=#{@rose_iris}"
set -gF pane-border-style "fg=#{@white_soft}"
